import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import { AuthProviderWithQueryClient } from "@/context/authContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { RegistrationProvider } from "@/context/registrationContext";


const dmSans = DM_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Health Linker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${poppins.variable}  antialiased`}>
        <RegistrationProvider>
          <AuthProviderWithQueryClient>
            {children}
            <ToastContainer
              limit={1}
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={true}
              closeOnClick
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
          </AuthProviderWithQueryClient>
        </RegistrationProvider>
      </body>
    </html>
  );
}
