import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";


const dmSans = DM_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Health Linker",
  description: "Generated by create next app",
  other: {
    "format-detection": "telephone=no, email=no, address=no",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${dmSans.variable} ${poppins.variable}  antialiased`}>
        <div suppressHydrationWarning>
          <main className="min-h-[calc(100vh-7rem)]">{children}</main>
        </div>
      </body>
    </html>
  );
}
